apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oj-lab.fullname" . }}-platform
  labels:
    oj-lab/application: platform
    {{- include "oj-lab.labels" . | nindent 4 }}
spec:
  {{- if not .Values.platform.autoscaling.enabled }}
  replicas: {{ .Values.platform.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      oj-lab/application: platform
      {{- include "oj-lab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.platform.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        oj-lab/application: platform
        {{- include "oj-lab.labels" . | nindent 8 }}
        {{- with .Values.platform.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "oj-lab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.platform.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.platform.securityContext | nindent 12 }}
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.platform.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.platform.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.platform.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.platform.resources | nindent 12 }}
          {{- with .Values.platform.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.platform.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
